### ISSUE TITLE
SSIM is weirdly high in the paper

### ISSUE THREAD

**Issue by guochengqian** [xingwz/End-to-End-JDNDMSR#3]
Dear authors, 
Thank you for your work.

I have run your pretrained weights (JDnDmSR+) and tested PSNR and SSIM using the standard MATLAB code. 
Here is what I get: 
PSNR:  26.88, SSIM: **0.8307**

the PSNR achieves a close value to the paper (26.89), but the SSIM is way lower than paper (**0.8922**). I guess you measured SSIM using some other implementation that might not be the same as used in the literature. 

Could you comment something on this?

**Comment by xingwz** [comment]
We just use the sim function of Matlab,
ssim = ssim(imageTest, imageGT, 'DynamicRange', 255);
Please we cut the border (=sf) of the images before the evaluation.

**Comment by guochengqian** [comment]
Hi @xingwz  thank you for the clarification.
